// <auto-generated />
using System;
using AM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AM.Infrastructure.Migrations
{
    [DbContext(typeof(AMContext))]
    partial class AMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AM.ApplicationCore.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Colis", b =>
                {
                    b.Property<string>("LivreurFk")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ClientFk")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<double>("Volume")
                        .HasColumnType("double");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LivreurFk", "ClientFk", "DateLivraison");

                    b.HasIndex("ClientFk");

                    b.ToTable("Colis");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Livreur", b =>
                {
                    b.Property<string>("CIN")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RaisonSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CIN");

                    b.ToTable("Livreur");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Vehicule", b =>
                {
                    b.Property<string>("Matricule")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VitesseLimite")
                        .HasColumnType("int");

                    b.HasKey("Matricule");

                    b.ToTable("Vehicule");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Conduite", b =>
                {
                    b.Property<string>("LivreursCIN")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VehiculesMatricule")
                        .HasColumnType("varchar(255)");

                    b.HasKey("LivreursCIN", "VehiculesMatricule");

                    b.HasIndex("VehiculesMatricule");

                    b.ToTable("Conduite");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Camion", b =>
                {
                    b.HasBaseType("AM.ApplicationCore.Domain.Vehicule");

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("NbrEssieux")
                        .HasColumnType("int");

                    b.ToTable("Camion", (string)null);
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Voiture", b =>
                {
                    b.HasBaseType("AM.ApplicationCore.Domain.Vehicule");

                    b.Property<int>("NbrPlaces")
                        .HasColumnType("int");

                    b.ToTable("Voiture", (string)null);
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Colis", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Client", "Client")
                        .WithMany("Colis")
                        .HasForeignKey("ClientFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Livreur", "Livreur")
                        .WithMany("Colis")
                        .HasForeignKey("LivreurFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Livreur");
                });

            modelBuilder.Entity("Conduite", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Livreur", null)
                        .WithMany()
                        .HasForeignKey("LivreursCIN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AM.ApplicationCore.Domain.Vehicule", null)
                        .WithMany()
                        .HasForeignKey("VehiculesMatricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Camion", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Vehicule", null)
                        .WithOne()
                        .HasForeignKey("AM.ApplicationCore.Domain.Camion", "Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Voiture", b =>
                {
                    b.HasOne("AM.ApplicationCore.Domain.Vehicule", null)
                        .WithOne()
                        .HasForeignKey("AM.ApplicationCore.Domain.Voiture", "Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Client", b =>
                {
                    b.Navigation("Colis");
                });

            modelBuilder.Entity("AM.ApplicationCore.Domain.Livreur", b =>
                {
                    b.Navigation("Colis");
                });
#pragma warning restore 612, 618
        }
    }
}
